# Generated by Django 5.0.6 on 2024-06-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai11', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='treatmentid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
