# Generated by Django 5.0.6 on 2024-06-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai11', '0002_alter_treatment_treatmentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiiregyosha',
            name='shiiretel',
            field=models.CharField(max_length=20),
        ),
    ]
