# Generated by Django 5.0.6 on 2024-07-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai11', '0003_alter_shiiregyosha_shiiretel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabyouin',
            name='tabyouintel',
            field=models.CharField(max_length=20),
        ),
    ]
